### ISSUE TITLE
Compatibility status of ERUPE9.2

### ISSUE THREAD

**Issue by GUEVARA1962** [HimmDawg/MHF-RoadshopEditor#1]
I found this tool useful. However, is it not yet compatible with ERUPE 9.2?

**Comment by HimmDawg** [comment]
I've checked the sql files for the erupe 9.2 database and the columns were indeed renamed, so no, it's not compatible. I'll have to update the column names in the model.

**Comment by GUEVARA1962** [comment]
Thank you for your quick response!

**Comment by GUEVARA1962** [comment]
Thank you for your quick response!
